server:
  port: 8080

spring:
  application:
      name: user-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

#actuator configurations
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

#resilience4j configurations
resilience4j:
  circuitbreaker:
    instances:
      user-service:
        registerHealthIndicator: true #this is for actuator
        eventConsumerBufferSize: 10 #
        failureRateThreshold: 60 #60% failure rate threshold
        minimumNumberOfCalls: 6
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 3s
        permittedNUmberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
